# config/packages/easy_admin.yml

easy_admin:
    site_name: 'Mangatech'
    design:
            brand_color: '#1ABC9C'
            color_scheme: 'light'
    entities:
        Mangas:
            class: App\Entity\Mangas
            list:
            # 'name' doesn't exist as a Doctrine entity property
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'author' }
                    - { property: 'cover', type: 'image', base_path: '%app.path.manga_covers%'  }
                    - { property: 'synopsis' }
                    - { property: 'genre' }
                    - { property: 'updatedAt', type: 'date' }
                    - { property: 'availability' }

        User:
            class: App\Entity\User
            list:
            # 'name' doesn't exist as a Doctrine entity property
            fields: ['id', 'name', 'lastname', 'username', 'email']




