# config/packages/easy_admin.yml

easy_admin:
    site_name: 'Mangatech'
    design:
            brand_color: '#1ABC9C'
            color_scheme: 'light'
    entities:
        Mangas:
            class: App\Entity\Mangas
            list:
            # 'name' doesn't exist as a Doctrine entity property
            fields: ['id', 'title', 'author', 'cover', 'email']

        User:
            class: App\Entity\User
            list:
            # 'name' doesn't exist as a Doctrine entity property
            fields: ['id', 'name', 'lastname', 'username', 'email']




