framework:
   router:
       strict_requirements: ~
#login:
#    pattern:   /login
#    defaults:  { _controller: OCUserBundle:Security:login }
#
#login_check:
#    pattern:   /login_check
#
#logout:
#    pattern:   /logout