security:
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        App\Entity\User: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            provider:  our_db_provider
            form_login:
                login_path: login
                check_path: login
                csrf_parameter: _csrf_security_token
                csrf_token_id: a_private_string
            logout:
                path: /logout
                target: /login
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
