<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPkxuaix\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPkxuaix/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPkxuaix.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPkxuaix\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPkxuaix\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Pkxuaix',
    'container.build_id' => 'cfb9ee0d',
    'container.build_time' => 1521103363,
));
